language: generic
include:
- os: linux
addons:
  apt:
    update: true
sudo: required
git:
  depth: 22
before_script:
- sudo apt-get install devscripts debhelper libfile-fcntllock-perl
script:
- chmod +x debuild.sh
- "./debuild.sh |& tee log.txt"
after_script:
- bash ./scripts/deploy.sh
notifications: 
slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
deploy:
  provider: releases
  api_key:
    secure: kK3lIim8KRT3eL3WlyznIFjg+NA1hgHKWHC7WwLV7pqrrgvxXNx5PmuQZj6Z7swtzTWIpmPGy8Vm8wCu6ibK4BDL2bl+pPjM7XcCEgPxGcrv4OHVfoj3DGpIcu+woNo+fr49E3TA/Bxsz90fLzuYEt8KRTXjKZftdtnhYOfTMwAn0g+cOBHWq2rom1mlPGOr5M5gClGgO++mNZ8eJAJ3U4tloTrICFHrFFaiaMyx1ozWYQz74gKKzxoiXn5hJSvfBemUuYL1i/98inlvmbC28aWBlVR/ICwGBNUdgowBwjA9AMPtJ02q9yAO0n5W8qfKMiILcvPlP74NN1mP9ox19tC7wqNpai4hmrLZCzB3qnESDdsq8xca3NtEyDw5K/PHgWcmUF3ObnEC1ki6INs/aiLdTUUpvrQWi4FzZZKt3XDoCHedk1Ig8eKWpqdrB0vPV15qICv0ZSOdlYr1Zn00+wmo8QCArx2jQVC5txNQFk5sFa0U3DcgY0cQrl89CuQGmz2/7sXEkZbK45luIu7jdh61v5rtIgpmh4JQgd0p/m91P7pbAW04LMndvXS/+RmxHJtQ8VGm53pryFe5Eg2YcqSP/Jb6/VLzAfoWIp7VtFe0hVrOg8NqpHa9DpkHDQZWal8+DY9nr1HKDWtp1/0pqoiuyAJLrM6yJeUAgMSvCvI=
  file: 
    - "./plymouth-meilix-logo_1.0-1_all.deb"
    - "./plymouth-meilix-text_1.0-1_all.deb"
  on:
    repo: pranav1698/meilix-artwork
    branch: deploy-error
